name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: musichin/ktlint-check@v1
        with:
          version: '0.45.2'

      - name: Build with Gradle
        run: ./gradlew build koverXmlReport --no-daemon
        env:
          JAVA_OPTS: '-Xmx2g -XX:MaxMetaspaceSize=512m'

      - uses: codecov/codecov-action@v2
