name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: musichin/ktlint-check@v2
        with:
          ktlint-version: '0.47.1'

      - name: Build with Gradle
        run: ./gradlew build koverXmlReport --no-daemon

      - uses: codecov/codecov-action@v3
